### ISSUE TITLE
[Slider] Component specs

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#224]
## Task description

- [x] Review and edit the component specs matching with the implementation of the component and using the [proper tables ](https://github.com/dxc-technology/halstack-style-guide/blob/master/contributing/content.md#spec-tables)and subsections for every spec (Typography, border, etc)
- [x] Update the component images following the [image contribution guidelines](https://github.com/dxc-technology/halstack-style-guide/blob/master/contributing/images.md)
- [x] Document the slider with input in a separate section instead of having it on the "User Interface considerations" section

## Related tasks

- [x] #311
- [x] #407 
- [x] #411
- [x] #424

**Comment by aweell** [comment]
Closed via #416 and #423

**Comment by aweell** [comment]
Closed via #416, #423 and #425

**Comment by aweell** [comment]
## [3.10.0] Updates

- [ ] Review :focus and :active states
- [ ] Update component images

**Comment by aweell** [comment]
Closed via #563
