### ISSUE TITLE
[Accordion] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#293]
## Story description

- [ ] Update component documentation page with corrected color specs

### React
```
    backgroundColor: globalTokens.white,
    arrowColor: globalTokens.purple,
    fontColorBase: globalTokens.darkGrey,
    hoverBackgroundColor: globalTokens.lightPurple,
    disabledFontColor: globalTokens.mediumGrey,
    customContentFontColor: "",
    assistiveTextFontColor: "",
    titleLabelFontColor: "",
    titleFocusBorderColor: globalTokens.purple,
    boxShadowColor: "#00000024",
    accordionGroupSeparatorBorderColor: "#00000024",
```

### Angular

```
  "--accordion-backgroundColor": globalTokens.white,
  "--accordion-arrowColor": globalTokens.purple,
  "--accordion-hoverBackgroundColor": globalTokens.lightPurple,
  "--accordion-fontColorBase": globalTokens.darkGrey,
  "--accordion-disabledFontColor": globalTokens.mediumGrey,
  "--accordion-titleFontColor": ""
  "--accordion-assistiveTextFontColor": "",
  "--accordion-customContentFontColor": "",
  "--accordion-headerFocusBorderColor": globalTokens.purple,
  "--accordion-boxShadowColor": "#00000024", 
  "--accordion-accordionGroupSeparatorBorderColor": "#00000024",
```

## Accordion color specs table

| Component token                                            | Element                                     | Core token                 | Value (HEX)  |
| ------------------------------------------- | ---------------------------- | -------------------- | ------------- |
| `titleLabelFontColor`                                      | Label                                         | `Hal-Grey-S-40`      | `#000000` | 
| `disabledColor`                                               | Label:disabled                         | `Hal-Grey-L-75`       | `#bfbfbf`    |
| `arrowColor`                                                    | Caret icon                                | `Hal-Purple-S-38`   | `#5f249f`    |
| `iconColor`                                                      | Custom icon                             | `Hal-Purple-S-38`   | `#5f249f`    |
| `assistiveTextFontColor`                                | Helper text                                | `Hal-Grey-S-40`      | `#666666`  |
| `hoverBackgroundColor`                               | Header background:hover      | `Hal-Purple-L-95`    | `#f2eafa`     |
| `titleFocusBorderColor`                                 | Header background:focus      | `Hal-Purple-S-38`   | `#5f249f`   |
| `backgroundColor`                                         | Container background            | `Hal-White`               | `#ffffff`       |
| `boxShadowColor`                                          | Container shadow                   | -  | #0000001a   |
| `accordionGroupSeparatorBorderColor`     | Separator                                  | -  | #0000001a   |

**Comment by GomezIvann** [comment]
Changes made on the Accordion advanced tokens:

- [ ] `disabledFontColor` renamed as `disabledColor`.
- [ ] `fontColorBase` token removed.
- [ ] `iconColor` token added.
- [ ] `customContentFontColor` has a new value: `#666666`.
- [ ] `assistiveTextFontColor` has a new value: `#666666`.
- [ ] `titleLabelFontColor` has a new value: `#666666`.

**Comment by aweell** [comment]
@GomezIvann 

`customContentFontColor` should be removed?

**Comment by GomezIvann** [comment]
Yes, i'm currently re-revisiting container components just for that labor.

**Comment by aweell** [comment]
- [ ] `titleLabelFontColor` should mantain: `#000000`.

[[Draft] Updated documentation](https://github.com/dxc-technology/halstack-style-guide/blob/component-accordion/guidelines/components/accordion/README.md#design-specifications)

**Comment by aweell** [comment]
Closed via #343
