### ISSUE TITLE
[Header] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#300]

**Comment by GomezIvann** [comment]
Changes made on the Header advanced tokens:

- [ ] `fontColorBase` token removed.
- [ ] `fontFamilyBase` token removed.
- [ ] `fontSizeBase` token removed.
- [ ] `dropdownBackgroundColor` token removed.
- [ ] `dropdownHoverBackgroundColor` token removed.
- [ ] `customContentFontFamily` has a new value: `Open Sans, sans-serif`.
- [ ] `customContentFontColor` has a new value: `#000000`.
- [ ] `customContentFontSize` has a new value: `16px`.
- [ ] `hamburguerFontFamily` has a new value: `Open Sans, sans-serif`.
- [ ] `hamburguerFontColor` has a new value: `#000000`.
- [ ] `menuCustomContentFontFamily` has a new value: `Open Sans, sans-serif`.
- [ ] `menuCustomContentFontColor` has a new value: `#000000`.
- [ ] `menuCustomContentFontSize` has a new value: `16px`.

**Comment by GauravMaurya0** [comment]
## React

backgroundColor: globalTokens.white,
customContentFontColor: "",
dropdownBackgroundColor: globalTokens.transparent,
dropdownHoverBackgroundColor: globalTokens.transparent,
fontColorBase: globalTokens.black,
hamburguerFocusColor: globalTokens.blue,
hamburguerFontColor: "",
hamburguerColor: globalTokens.black,
hamburguerHoverColor: globalTokens.mediumGreyBlack,
menuBackgroundColor: globalTokens.white,
menuCustomContentFontColor: "",
overlayColor: globalTokens.softBlack,
underlinedColor: globalTokens.black,


## Angular

"--header-backgroundColor": globalTokens.white,
"--header-underlinedColor": globalTokens.black,
"--header-fontColor": globalTokens.black,
"--header-backgroundColorMenu": globalTokens.white,
"--header-fontColorMenu": globalTokens.black,
"--header-hamburguerColor": globalTokens.black,
"--header-hoverHamburguerColor": globalTokens.mediumGreyBlack,
"--header-overlayColor": globalTokens.softBlack,
"--header-focusColor": globalTokens.blue,



## Table color specs table

| Component token                         | Element       | Core token | Value |
| -----------------------------   | ----------- | -------- | --------- |
| `backgroundColor` | Fill | `Hal-White` | `#ffffff` |
| `underlinedColor` | Label | `Hal-Black` | `#000000` |
| `dropdownBackgroundColor` | Fill | - | `transparent` |
| `dropdownHoverBackgroundColor` | Fill | - | `transparent` |
| `fontColorBase` | Label | `Hal-Black` | `#000000` |
| `hamburguerFocusColor` | menu:focus | `Hal-Blue-L-50` | `#0095ff ` |
| `hamburguerFontColor` | menu | - | - |
| `hamburguerColor` | menu | `Hal-Black` | `#000000` |
| `hamburguerHoverColor` | menu:hover | `Hal-Grey-S-40` | `#666666` |
| `menuBackgroundColor` | fill | `Hal-White` | `#ffffff` |
| `menuCustomContentFontColor` | Label | `Hal-Black` | `#000000` |
| `overlayColor` | fill | `Hal-Grey-L-95` | `#f2f2f2` |
