### ISSUE TITLE
[Chip] Color specs update

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-style-guide#348]
#### On-light

| Component token           | Element                   | Token                   | Value     |
| :------------------------ | :------------------------ | :---------------------- | :-------- |
| `backgroundColor`         | Chip container            | `color-grey-200`        | `#e6e6e6`   |
| `disabledBackgroundColor` | Chip container:disabled   | `color-grey-100`        | `#f2f2f2`   |
| `fontcolor`               | Label                     | `color-black`           | `#000000`	  |
| `disabledFontcolor`       | Label:disabled            | `color-grey-500`        | `#999999`	  |
| `focusColor`              | Focus outline             | `color-blue-600`        | `#0095ff`	  |
| `iconColor`               | Icon                      | `color-black`           | `#000000`	  |
| `disabledIconColor`       | Icon:disabled             | `color-grey-500`        | `#999999`	  |

#### On-dark

| Component token                 | Element                   | Token                   | Value     |
| :------------------------------ | :------------------------ | :---------------------- | :-------- |
| `backgroundColorOnDark`         | Chip container            | `color-grey-700`        | `#666666`   |
| `disabledBackgroundColorOnDark` | Chip container:disabled   | `color-grey-800`        | `#4d4d4d`   |
| `fontcolorOnDark`               | Label                     | `color-white`           | `#ffffff`	  |
| `disabledfontcolorOnDark`       | Label:disabled            | `color-grey-500`        | `#999999`	  |
| `focusColorOnDark`              | Focus outline             | `color-blue-600`        | `#0095ff`	  |
| `iconColorOnDark`               | Icon                      | `color-white`           | `#ffffff`	  |
| `iconColorOnDark`               | Icon:disabled             | `color-grey-500`        | `#999999`	  |

Changes made on the Chip advanced tokens:

- [ ] `backgroundColor` has a new value: `#e6e6e6`.
- [ ] `disabledBackgroundColor` has a new value: `#f2f2f2`.
- [ ] `disabledFontColor` has a new value: `#999999`.
- [ ] `borderRadius` has a new value: `80px`.
- [ ] `borderThickness` has a new value: `0px`.
- [ ] `contentPaddingLeft` has a new value: `16px`.
- [ ] `contentPaddingRight` has a new value: `16px`.
- [ ] `contentPaddingTop` has a new value: `0px`.
- [ ] `contentPaddingBottom` has a new value: `0px`.
- [ ] New `focusColor` token added with value `#0067b3`.
- [ ] New `disabledIconColor` token added with value `#999999`.
- [ ] New `iconColor` token added with value `#000000`.
- [ ] New `iconSpacing` token added with value `8px`.
- [ ] `iconPaddingLeft` token removed.
- [ ] `iconPaddingRight` token removed.
- [ ] `height` token removed.

**Comment by aweell** [comment]
## Story description

- [ ] Update component documentation page with corrected color specs


## Accordion color variables

### React
```
    backgroundColor: globalTokens.darkWhite,
    borderColor: globalTokens.transparent,
    fontColor: globalTokens.black,
    disabledBackgroundColor: globalTokens.mediumWhite,
    disabledFontColor: globalTokens.lighterBlack,
```

### Angular

```
  "--chip-backgroundColor": globalTokens.darkWhite,
  "--chip-borderColor": "transparent",
  "--chip-fontColor": globalTokens.black,
  "--chip-disabledBackgroundColor": globalTokens.mediumWhite,
  "--chip-disabledFontColor": globalTokens.lighterBlack,
```

## Accordion color specs table

Component token | Element | Token | Value
-- | -- | -- | --
`backgroundColor` | Chip container | `Hal-Grey-S-90` | `#e6e6e6`
`disabledBackgroundColor` | Chip container:disabled | `Hal-Grey-S-95` | `#f2f2f2`
`fontColor` | Label | `Hal-Black` | `#000000`
`disabledFontColor` | Label:disabled | `Hal-Grey-L-60` | `#999999`
`focusColor` | Focus outline | `Hal-Blue-s-35` | `#0067b3`
`iconColor` | Icon | `Hal-Black` | `#000000`
`disabledIconColor` | Icon:disabled | `Hal-Grey-L-60` | `#999999`

**Comment by aweell** [comment]
Closed via #514
