### ISSUE TITLE
[Input] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#354]

**Comment by GomezIvann** [comment]
Changes made on the Input advanced tokens:

- [ ] `fontColorBase` token removed.
- [ ] `fontColorBaseOnDark` token removed.
- [ ] `fontSizeBase` token removed.
- [ ] `assistiveTextFontColor` has a new value: `#000000`.
- [ ] `assistiveTextFontColorOnDark` has a new value: `#ffffff`.
- [ ] `prefixIconColor` has a new value: `#000000`.
- [ ] `prefixIconColorOnDark` has a new value: `#ffffff`.
- [ ] `prefixLabelFontColor` has a new value: `#000000`.
- [ ] `prefixLabelFontColorOnDark` has a new value: `#ffffff`.
- [ ] `sufixIconColor` has a new value: `#000000`.
- [ ] `sufixIconColorOnDark` has a new value: `#ffffff`.
- [ ] `sufixLabelFontColor` has a new value: `#000000`.
- [ ] `sufixLabelFontColorOnDark` has a new value: `#ffffff`.
- [ ] `underlineColor` has a new value: `#000000`.
- [ ] `underlineColorOnDark` has a new value: `#ffffff`.
- [ ] `underlineFocusColor` has a new value: `#000000`.
- [ ] `underlineFocusColorOnDark` has a new value: `#ffffff`.
- [ ] New `labelFontColor` token added with value: `#000000`.
- [ ] New `labelFontColorOnDark` token added with value: `#ffffff`.
- [ ] New `labelFontStyle` token added with value: `normal`.
- [ ] New `labelFontWeight` token added with value: `400`.
- [ ] New `customContentFontColor` token added with value: `#000000`.
- [ ] New `customContentFontColorOnDark` token added with value: `#ffffff`.
- [ ] New `customContentFontSize` token added with value: `1rem`.
- [ ] New `customContentFontStyle` token added with value: `normal`.
- [ ] New `customContentFontWeight` token added with value: `400`.
