### ISSUE TITLE
[Alert] Update component documentation to new template

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#372]
## Task description

- [x] Add "Types" section
- [x] Add "Usage" section
- [x] Add "Anatomy" section
- [x] Add "Accessibility" section
- [x] Update "Modes" to "Variants" section
- [x] Remove "User interface considerations"

**Comment by aweell** [comment]
Closed via #374
