### ISSUE TITLE
[Slider] Update component documentation to new template

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#407]
## Task description

In order to update the documentation to the new template the following items should be completed:

- [x] Remove appearance section
- [x] Rename "Modes" to "Variants" section
- [x] Rename "User Interface Design Considerations" to "Usage" and move it after the component title and description
- [x] Rename "Design tokens" section to "Color" and place it as a subsection of "Design specifications"
- [x] Add implementation links to "Links and references" section
- [ ] Update specs table dividing elements by property
- [ ] Update usage section

**Comment by aweell** [comment]
Closed via #416 and #423
