### ISSUE TITLE
[Input-password] Component documentation

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#420]
## Story description

Create documentation for the `input-password` component.

## Tasks

- [x] Add `README.md` template and images folder
- [x] Add `input-password_images.xd` file
- [x] Add `miniature.png` file

**Comment by aweell** [comment]
Closed via #454
