### ISSUE TITLE
[Dialog] Documentation review

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#443]
## Story description

Review "Usage" and "Combining whit other UI elements" sections to provide more descriptive guidance about how to use the component. Update component specs dividing "Specifications for desktop and tablet (landscape mode)" in `typography`, `spacing`, and `size` spec tables.

### Tasks

- [x] Update component specs
- [x] Review "Usage" section
- [x] Add "Accessibility" section

"Combining whit other UI elements" section will be removed until we have a clear guidelines about how the elements load when already having an overlay

**Comment by aweell** [comment]
Closed via #564
