### ISSUE TITLE
[Button] Variant tokens update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#499]
## Story description

In order to accommodate `onDark` variant tokens, there is a need to make a change in the `:hover` and `:focus` state tokens of the secondary button variant.

### Tasks

- [x] Update documentation images
- [x] Update `button_images.xd` file
- [x] Update secondary color specs

**Comment by aweell** [comment]
Closed via #500
