### ISSUE TITLE
[Toggle-group] Update component documentation to new template

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#501]
## Story description

Update component documentation following the new template

### Tasks

- [x] Rename modes as variants
- [x] Add anatomy section
- [x] Update component specs

**Comment by aweell** [comment]
Closed via #502
