### ISSUE TITLE
[Button] Add button Icon variants as component

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#521]
## Story description

Add icon type to the Halstack library components

### Tasks

- [x] Add `button / primary / icon / onLight / desktop`
- [x] Add `button / primary / icon / onDark / desktop`
- [x] Add `button / secondary / icon / onLight / desktop`
- [x] Add `button / secondary / icon / onDark / desktop`
- [x] Add `button / text / icon / onLight / desktop`
- [x] Add `button / text / icon / onDark / desktop`

**Comment by aweell** [comment]
Closed via #550
