### ISSUE TITLE
[Button] Component updates

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#547]
## Story description

Add as a component the button icon variants in the UI-Kit, update interactive styles, and reduce component width

### Tasks

- [x] Add `button / variant / Icon / onLight / desktop` components
- [x] Update component padding documentation specs
- [x] Update component documentation images
- [x] Update other compound components that reuse the button
- [x] Update other compound components documentation images that reuse the button
   * Dialog
   * Upload
- [x] Update button XD shareable link

**Comment by aweell** [comment]
Closed via #548

**Comment by aweell** [comment]
Closed via #581
