### ISSUE TITLE
[Accordion] Focus state

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#583]
## Story description

In order to be coherent with the rest of the components, the focus state need to be changed to an outline 2px `color-blue-600`

### Tasks

- [x] Update UI-Kit accordion main component
- [x] Update `accordion_images.xd`
- [x] Update documentation images and component specs
- [x] Update XD shareable link

**Comment by aweell** [comment]
Closed via #584
