### ISSUE TITLE
Updates in design contribution

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#594]
## Story description

Our contribution documentation is currently focused on adding new components, sometimes it's needed to add features to components to already exist, in this new section, we will provide information about the process to follow when contributing back.

### Tasks

- [x] Add new variant subsection
- [x] Modifying an existing variant section
- [x] Explanation about how to document the changes
- [x] Add UI-Kit color legend to the documentation
