### ISSUE TITLE
[Header] Update documentation to new template

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#598]
## Story description

The header component documentation needs to be updated following the new documentation template.

### Tasks

- [x] Update anatomy section
- [x] Replace "User interface considerations" as "Usage"
- [x] Update component spec tables

### Related tasks

- [x] #300
