### ISSUE TITLE
[Slider] Add label and helper text

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#619]
## Story description

In order to provide an accessible component, we need to add the label to the slider component since there's no possibility to use the HTML `for` to link an external label to de component `id`.

### Tasks

- [x] Update UI-Kit component
- [x] Update documentation images
- [x] Add typography specs
- [x] Modify component status 🟣

**Comment by aweell** [comment]
Closed via #620
