### ISSUE TITLE
[Docs] Add deprecated alert to v3 components

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#653]
## Story description

Include a message to redirect to the new components in the deprecated documentation pages

## Tasks

- [x] Add message to v3_text-input
- [x] Add message to v3_date
- [x] Add message to v3_autocomplete

**Comment by aweell** [comment]
Closed via #654
