### ISSUE TITLE
[Release] Fixes for v4.0.0

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#656]
## Story description

Fixes in component documentation for release 4.0.0

## Tasks

- [x] Edit wrong naming references in input file component
- [x] Add divider specs and update listItem `:focus` state
- [x] Add `color-grey-100` as background-color to all input `:disabled` states
- [x] Review new released component tokens
- [x] Update links and catalog.json

**Comment by GomezIvann** [comment]
Summary:

- `labelOptiona` token is really needed? In the other components with this label for optional fields we just have `optionalLabelFontWeight`.
- `errorColor` instead of `errorMessageColor` and `errorIconColor` as in other input components.
- Should we add `disabledCollapseIndicatorColor` token? Which is the collapse indicator color when it is disabled?
- `listItemXXX` tokens are called in the Autosuggest `optionListXXX`, should we unify them? For example:
	- optionListBackgroundColor --> itemListBackgroundColor
	- optionListBorderColor --> itemListBorderColor
- CamelCase errors in some tokens, for example, `unselectedactivelistItemBackgroundColor`.
- What are the styles for the Selection Indicator when the multi select is disabled? Also, the Selection Indicator examples are still with the old border-radius.
- Disabled select bakcground color is still as the previous version in the examples.
- Multiple Selection examples are wrong:

![image](https://user-images.githubusercontent.com/44321109/148087562-d84fcc61-4a00-4bdb-84df-74e3775dc4c5.png)
The correct example:

![image](https://user-images.githubusercontent.com/44321109/148087437-f9da2a75-2ce4-4bc3-841c-c27c72ba07ab.png)

- `labelFontXXX` tokens are twice in the _Typography_ section.
- We should add `valueLineHeight` to be consistent with the other typography tokens.
- In the other new inputs we are not giving tokens for the placeholder, should we follow that strategy also here? Or should it use the `valueFontXXX` tokens as in the other components?
- Should we remove `errorMessageFontXXX` tokens? I think we shoul allow users to change the way the error looks, that could we inconsistent with the other fields such us text-input, textarea, etc.
- The _Size_ table is still using the old values.

**Comment by aweell** [comment]
Going point by point:

## Select

### Token naming fixes

> `labelOptiona` token is really needed? In the other components with this label for optional fields we just have `optionalLabelFontWeight`.

- [x] Removed `labelOptiona`. Added `optionalLabelFontWeight`

> CamelCase errors in some tokens, for example, `unselectedactivelistItemBackgroundColor`.

- [x] Fix camelCase token naming errors


### Selection indicator

> Should we add `disabledCollapseIndicatorColor` token? Which is the collapse indicator color when it is disabled?

There is a token called `disabledColor` that affects all disabled elements. Maybe we need to divide it a go element by element

> What are the styles for the Selection Indicator when the multi select is disabled? Also, the Selection Indicator examples are still with the old border-radius.

- [x] Change `border-radius` to 0.125rem
- [x] Add border-radius properties to the documentation
- [x] Added selection indicator disabled state

### List items

> `listItemXXX` tokens are called in the Autosuggest `optionListXXX`, should we unify them? For example:
> `optionListBackgroundColor` here is itemListBackgroundColor.
> `optionListBorderColor` here is itemListBorderColor.
> etc.

Agree, we need to unify them, here is what I think (open to suggestions):
* Dialog for the list: `listDialogXyz`
* Item of the list: `listItemXyz`

### Documentation images

> Multiple Selection examples are wrong:

- [x] Fix images

> `labelFontXXX` tokens are twice in the Typography section.

They meant to be the label optional tokens

- [x] Add optional to duplicated label tokens

> We should add valueLineHeight to be consistent with the other typography tokens.

**Comment by aweell** [comment]
Removed 

* `optionalLabelfontWeight`
* `disabledSelectionIndicatorActionColor`
* `optionallabelFontSize`   
* `optionallabelFontStyle`   
* `optionallabelLineHeight`   

Added

* `selectionIndicatorFontColor`
* `actionIconColor`
* `focusListOptionBorderColor`               
* `systemMessageFontColor` 
* `collapseIndicatorColor`
* `errorIconColor`
* enabledSelectionIndicatorActionIconColor`
* `hoverSelectionIndicatorActionIconColor`          
* `activeSelectionIndicatorActionIconColor`

**Comment by aweell** [comment]
## Text-input

- [ ] `listOptionDividerColor` instead of `listOptionBorderColor`

## Autosuggest

- [ ] System error example image
- [ ] Add: `errorListDialogBackgroundColor`, `errorListDialogBorderColor` and `errorListDialogFontColor`
- [ ] Add: `focusListOptionBorderColor`

**Comment by aweell** [comment]
## File input

- [ ] Change `focusDropBackgroundColor` to `dragOverDropBackgroundColor`

**Comment by GomezIvann** [comment]
**SELECT**
- [ ] `listGroupItemFontWeight` changed to `listGroupLabelFontWeight`.
- [ ] `unselectedHoverlistOptionBackgroundColor` camel case, replace by `unselectedHoverListOptionBackgroundColor`.
- [ ] `unselectedActivelistOptionBackgroundColor` camel case, replace by `unselectedActiveListOptionBackgroundColor`.
- [ ] `disabledInputBackgroundColor` has the value: `#999999`, which is a very strong grey, shouldn't it be `#f2f2f2` linke in the textInput?

**Comment by GomezIvann** [comment]
More Select things:

- Currently i can't implement the token `focusActionIconColor` because is not focusable right now.
- Is there a situation where `Clear searchbox action`  and the searchbox itself can be shown as disabled? If not, are `disabledActionXXX` tokens really necessary?
- `actionBackgroundColor` is missing (value: `transparent`).
- `valueLineHeight` is only implemented for this component, should we remove it?.

**Comment by aweell** [comment]
> Currently i can't implement the token `focusActionIconColor` because is not focusable right now.

Removed `focusActionIconColor`

> Is there any situation where the clear searchbox action and the searchbox itself can be shown as disabled? If not, are disabledActionXXX tokens really necessary?

Removed `disabledActionBackgroundColor`

> `actionBackgroundColor` is missing (value: transparent).

Added `actionBackgroundColor`

> `valueLineHeight` is only implemented for this component, should we remove it?

Removed `valueLineHeight`

inputBorderRadius and actionBorderRadius aren't as tokens in the other new field components, should we add them there or remove them here?

**Comment by aweell** [comment]
## Text-input

- [x] Added `InputMarginTop` and `InputMarginBottom` tokens a82a08a359a91142c6244b6d03fc1f9369a71e24 1b330580ff4fafadc498860d7eac9259ac5c8841

All components that reuse text-input styles will have these spacing tokens

**Comment by aweell** [comment]
Closed via #657
