### ISSUE TITLE
[Paginator] UI-kit component

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#679]
## Story description

Update paginator component to match the current implementation

### Tasks

- [x] Use the spacing scale to adapt the internal element's `margin` and `padding` 
- [x] Create paginator_images.xd file
- [x] Update UI-kit version with the latest component update

**Comment by aweell** [comment]
Closed via #681
