### ISSUE TITLE
[Slider] Update disabled styles

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#693]
## Story description

Slider label and helper text element are not following the global styles for disabled elements

### Tasks

- [x] Update documentation images and UI Kit component
- [x] Add `disabledLabelFontColor` and `disabledHelperTextFontColor`
- [x] Add tokens for min and max labels

**Comment by GomezIvann** [comment]
Proposal for min and max labels tokens: `limitValuesFontXXX` and `disabledLimitValuesFontColor`.

**Comment by aweell** [comment]
When we think we have all the component tokens we need:

![image](https://user-images.githubusercontent.com/44420072/152833592-3320e0b9-2d5a-4263-b2e1-1b66c53fccaf.png)

**Comment by aweell** [comment]
Shouldn't be added limitValuesFontColor as globalTokens.color_black (`#000000`) also?

**Comment by GomezIvann** [comment]
Yes, I already have that token but it wasn't in the screenshot, sorry!

**Comment by aweell** [comment]
Closed via #694
