### ISSUE TITLE
[File-input] Update focus state in action sub-component

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#697]
## Story description

The current `:focus` state of the file-input action sub-component is not following the standard approach of other input components

### Tasks

- [x] Update UI-Kit component
- [x] Update documentation images
- [x] Update component token specifications

**Comment by aweell** [comment]
Closed via #698
