### ISSUE TITLE
Create doc page for ApplicationLayout component

### ISSUE THREAD

**Issue by jsuarezgonz** [dxc-technology/halstack-style-guide#789]
## Story description

The current documentation doesn't have a page for the application-layout component

### Tasks

- [x] Create the application-layout doc page
- [x] Create component specs and anatomy images
- [x] Add the draft as a .tsx page in the next.js site
